apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  type: Opaque
  metadata:
    name: searchpe-config
    labels:
      app: searchpe
  data:
    searchpe-stages.yml: cHJvamVjdDoKICBzdGFnZTogcHJvZHVjdGlvbgpzd2FybToKICBkYXRhc291cmNlczoKICAgIGRhdGEtc291cmNlczoKICAgICAgUmVwZWlkRFM6CiAgICAgICAgZHJpdmVyLW5hbWU6IHBvc3RncmVzcWwKICAgICAgICB1c2VyLW5hbWU6IHNlYXJjaHBlCiAgICAgICAgcGFzc3dvcmQ6IHNlYXJjaHBlCiAgICAgICAgY29ubmVjdGlvbi11cmw6IGpkYmM6cG9zdGdyZXNxbDovL3NlYXJjaHBlLWRiOjU0MzIvc2VhcmNocGUKcmVwZWlkOgogIHNjaGVkdWxlcjoKICAgIGVuYWJsZWQ6IHRydWUKICAgIHRpbWVab25lOiAiQW1lcmljYS9MaW1hIgogICAgaW5pdGlhbEV4cGlyYXRpb246ICIwMDowMDowMCIKICAgIGludGVydmFsRHVyYXRpb246IDM2MDAwMDAKICAgIGV4cGlyYXRpb25UaW1lSW5NaWxpczogMTA4MDAwMDAKICAgIGRvd25sb2FkRmlsZUxvY2F0aW9uOiAic3VuYXQuemlwIgogICAgdW56aXBGaWxlTG9jYXRpb246ICJzdW5hdC50eHQiCiAgICBkYXRhYmFzZVVSTDogImh0dHA6Ly93d3cyLnN1bmF0LmdvYi5wZS9wYWRyb25fcmVkdWNpZG9fcnVjLnppcCIKICAgIGZpbGVDaGFyc2V0OiAiSVNPLTg4NTktMSIKICAgIGZpbGVSb3dTa2lwOiAxCiAgICBmaWxlQ29sdW1uU2VwYXJhdG9yOiAiXFx8IgogICAgZmlsZUNvbHVtbkhlYWRlcnM6ICJSVUN8Tk9NQlJFIE8gUkFaw5NOIFNPQ0lBTHxFU1RBRE8gREVMIENPTlRSSUJVWUVOVEV8Q09ORElDScOTTiBERSBET01JQ0lMSU98VUJJR0VPfFRJUE8gREUgVsONQXxOT01CUkUgREUgVsONQXxDw5NESUdPIERFIFpPTkF8VElQTyBERSBaT05BfE7Dmk1FUk98SU5URVJJT1J8TE9URXxERVBBUlRBTUVOVE98TUFOWkFOQXxLSUzDk01FVFJPIgogICAgZmlsZUNvbHVtblZhbHVlczogInJ1YyxyYXpvblNvY2lhbCxlc3RhZG9Db250cmlidXllbnRlLGNvbmRpY2lvbkRvbWljaWxpbyx1YmlnZW8sdGlwb1ZpYSxub21icmVWaWEsY29kaWdvWm9uYSx0aXBvWm9uYSxudW1lcm8saW50ZXJpb3IsbG90ZSxkZXBhcnRhbWVudG8sbWFuemFuYSxraWxvbWV0cm8i
